[functions.setup-school]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.resend-verification]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.change-password]
verify_jwt = true
